### PR TITLE
Changed Navbar + Added Webseries + Added Anime Section + Changed Font

### PR DESCRIPTION
**Pull request by PSS2134**
Issue #42 
1. [x] Changed Navbar, Added Wishlist Button and SignIn
2. [x] Changed FontStyle
3. [x] Added 5 Webseries Each in Hollywood and Tollywood Section
4. [x] Added a seperate Anime Section and added  animes

Here is the video 
[screen-capture (1).webm](https://github.com/vikhyatsingh123/Movies-Collection/assets/101321904/840134c7-9162-4bd7-9a93-24f19954a6e2)

 @vikhyatsingh123

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
@PSS2134 What does this signin do here. There is no value of adding that

**Comment by PSS2134** [comment]
So that a person can view his wishlist after sign in , so that the wishlist will get personalized? @vikhyatsingh123

**Comment by vikhyatsingh123** [comment]
ok, I didn't see your another created issue. Resolve conflicts, I will merge it

**Comment by PSS2134** [comment]
Conflicts resolved @vikhyatsingh123

**Pull request merged**
