### PR TITLE
Enhanced overall user interface

### PR DESCRIPTION
**Pull request by Harsh2504**
All **UI Enhancements** mentioned in the issue were made:

1. **Navbar** should have **website title**
2. Navbar **styling , hover effects , active tab**
3. **Dark mode to work properly on whole website**
4. Carsouel improvement (**picture scaling** )
5. Improve **overall styling** of webpage (buttons , fonts ,etc);

**Additional changes :**
1.Added **text above carsoue**l  (Website title and subtitle)
2.About pages **image and it design** updated 
3.Added **links** to your **github** and **LinkedIn**  
4. Also **integrated** your latest PR of **suggestion pages** and **Enhanced its user interface too...**

I have **spent lot of time** for this contribution and **improved this a lot** by doing **additional changes** . 
I hope these additional changes will be considered for **Extra points**.  I will be happy if you do so **i loved contributing to your project** .
**Thank You!!!**

### CODE REVIEW

**Comment by Harsh2504** [comment]
image
image
image
image
image

**Comment by Harsh2504** [comment]
@vikhyatsingh123  After this PR merged i will integrate the movies information pages too shortly ..... Issue No. #20

**Comment by vikhyatsingh123** [comment]
Great work! I appreciate it.

**Comment by Harsh2504** [comment]
> Great work! I appreciate it.

@vikhyatsingh123 I just wanted to ask there are also points for raising issue right ?!
 If yes, I have raised many issues on your projects (naruto , movies collection , slugterra) plz check it 😊

**Comment by vikhyatsingh123** [comment]
Ok, I will give points. Can you tell me when is the last date of contribution

**Comment by Harsh2504** [comment]
> Ok, I will give points. Can you tell me when is the last date of contribution

28 December

**Comment by Harsh2504** [comment]
> Great work! I appreciate it.
> Ok, I will give points. Can you tell me when is the last date of contribution

haven't received any points for the PR and the other issues raised too??

**Pull request merged**
