### PR TITLE
Added:  Bollywood WebSerieses

### LINKED ISSUE #49: Add more bollywood series
There are only three now!

Please asign me for codepeak

### PR DESCRIPTION
**Pull request by AaadityaG**
Adding 21 Cards for Bollywood WebSeries Section..

Close #49

I am participating in Codepeak

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
@AaadityaG resolve conflicts

**Comment by AaadityaG** [comment]
can you suggest what should I do

**Review by AaadityaG — COMMENTED** [review]
@vikhyatsingh123 Its Done!

**Comment by AaadityaG** [comment]
Reopening new PR

**Pull request closed without merging**
