### PR TITLE
Added new card X banner structure

### PR DESCRIPTION
**Pull request by Sami3160**
Added some cards related to entertainment domain and especially the tabs you added...
-Animation also added
-Its responsive
-Relates to your movies
-Slide able 
Screenshot (163)
and here is video, please check all video it took a lot of efforts as react newbie...I hope you are gonna like this😁

https://github.com/vikhyatsingh123/Movies-Collection/assets/110652247/428adb1e-6d5a-43c2-9c1d-e1b51c2bcbc4

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
@Sami3160 can you resolve conflicts

**Comment by Sami3160** [comment]
> @Sami3160 can you resolve conflicts

@vikhyatsingh123  all merge conflicts are resolved

**Comment by Sami3160** [comment]
> > @Sami3160 can you resolve conflicts
> 
> @vikhyatsingh123 all merge conflicts are resolved

@vikhyatsingh123 all conflicts are resolved, please merge it before more conflicts arises.. plz sir

**Comment by Sami3160** [comment]
> @Sami3160 can you resolve conflicts

@vikhyatsingh123  excuse me sir, could you please merge my pr before any more merge conflicts appear? And i want to work on your project more on UI, so please accept this one😄

**Pull request merged**
