### PR TITLE
New Hollywood movie added 'EndGame'

### PR DESCRIPTION
**Pull request by Sami3160**
Issue #1 
In Hollywood.jsx i have added new movie. Please merge😊

### CODE REVIEW

**Comment by vikhyatsingh123** [comment]
@Sami3160 why did you closed the issue

**Comment by Sami3160** [comment]
> @Sami3160 why did you closed the issue

i dont know i did it mistakenly :(, wait please let me fix it

**Comment by Sami3160** [comment]
> @Sami3160 why did you closed the issue

yeah i remember, this commit had some branch conflicts...so my friend told me to create new pull request and close this...im sorry if i did something wrong, im still learning github

**Comment by vikhyatsingh123** [comment]
@Sami3160 ok no problem.
If you are seeing some branch conflicts then you can simply take pull from main branch then commit it. It will solve your problem.

**Pull request closed without merging**
